### ISSUE TITLE
Newer elixir versions

### ISSUE THREAD

**Issue by Linuus** [ScenicFramework/scenic_new#37]
The readme says that Scenic only works with Elixir 1.7 and OTP 21.

I can’t find any issues here on github on what’s not working on later versions. Is there such a list somewhere?

**Comment by Linuus** [comment]
I just installed scenic and generated a nerves app. Now I get this warning: `warning: the dependency :scenic requires Elixir "~> 1.8" but you are running on v1.7.4`. So I guess the Readme here is wrong then?

**Comment by Eiji7** [comment]
@Linuus If we take a look at `mix.exs] in [scenic]() repository

**Comment by Eiji7** [comment]
@Linuus If we take a look at [mix.exs](https://github.com/boydm/scenic/blob/master/mix.exs) in [scenic](https://github.com/boydm/scenic) repository then we would find:
```elixir
defmodule Scenic.Mixfile do
  # …

  @elixir_version "~> 1.8"
  # …

  def project do
    [
      # …
      elixir: @elixir_version,
      # …
    ]
  end
  # …
end
```
Which means that `scenic` requires `elixir` in at least `1.8` version.

Then we can take a look at [history](https://github.com/boydm/scenic/commits/v0.10/mix.exs) of that file. and finally we would see:

> …
> 
> back to 1.8
boydm committed on 10 Mar
> 
> turn off build_embedded
boydm committed on 10 Mar
> 
> try building under 1.7
boydm committed on 10 Mar
> 
> so to elixir 1.8
boydm committed on 10 Mar…
> 
> …

Which gives as a hint that `scenic` not longer compiles under `elixir` in version `1.7`. Most probably it uses some new `elixir` API or there were a bug in `elixir` fixed in version `1.8`.

Looks like that `scenic` would require `elixir` in version `1.8` and it won't be changed.

@boydm Looks like we would need to update some parts of code (like templates in examples) + documentation.

**Comment by boydm** [comment]
Of course... I don't exactly remember what the reason for going to 1.8 was...

**Comment by Linuus** [comment]
Cool :)

Just to be clear, this is the part that confused me: https://github.com/boydm/scenic_new/blob/master/README.md#erlangelixir-versions
